### ISSUE TITLE
Todolist Milestone 1

### ISSUE THREAD

**Issue by TheFitzZZ** [TheFitzZZ/Warthog#5]
- [x] DM Event creator with more options
- [x] DM Eventcreator when not enough parameters are given
- [x] Extend possible parameters to include more options
- [x] Secure debug commands to bot owner
- [x] Put creator only into relevant commands (edit, del)
- [x] Add an admin group to security protected commands (edit, del)
----------------
- [x] Delete events
- [x] Delete security check (server based)
----------------
- [x] Add detailed text
- [x] Add briefing URL
- [x] Add Discord Invite URL
- [x] Add max attendees
----------------
- [x] Implement Waitlist with DM to user that
- [x] Add user "will attend" options (and removal)
----------------
- [x] Edit text passages
----------------
- [x] Provide custom help, move auto help to different command
- [x] Write proper readme on github page
- [x] Don't list events in the past
- [x] Make eventlist look nicer
- [x] Single event info
