### ISSUE TITLE
Todolist Milestone 2

### ISSUE THREAD

**Issue by TheFitzZZ** [TheFitzZZ/Warthog#6]
- [ ] Make update announcement configurable
----------------
- [ ] Fix config file usage
----------------
- [ ] Add group based security check that works on multiple servers
----------------
- [ ] Catch bad entries and replace error msges
----------------
- [ ] Add DM reminder for event (x hours b4 event)
- [ ] Add option to disable reminder for event AND global
----------------
- [ ] Set calendar channel
- [ ] Add removal commands to keep channel clean
- [ ] Event announce feature for creator ->  !announce id #channel
- [ ] Edit attendeelist
----------------
- [ ] Allow BOT DM commands where it compares on what servers the user is on and responds accordingly
----------------
- [ ] Make the help more pretty :-)
